import type { PPAPCase } from "./types.js";

const NOW = "2026-08-09T10:00:00.000Z";

/** Development seed case PP-10482 for local demos and tests. */
export function createDemoCase(): PPAPCase {
  return {
    caseId: "PP-10482",
    createdAt: NOW,
    updatedAt: NOW,
    supplier: {
      name: "Mechatronik Components GmbH",
      supplierId: "SUP-0084",
      manufacturingLocation: "Stuttgart, Germany",
    },
    part: {
      number: "SMH-44721",
      name: "Steering Motor Housing",
      drawingRevision: "C",
      customerPartNumber: "OEM-SMH-44721",
    },
    submission: {
      customer: "Demo Automotive OEM",
      reason: "Engineering Change",
      profile: "DEMO_LEVEL_3",
      submissionDate: "2026-08-01",
      engineeringChangeReference: "ECN-2844",
    },
    documents: [
      {
        id: "DOC-DRAWING",
        fileName: "SMH-44721_RevC_Drawing.pdf",
        type: "DRAWING",
        title: "Engineering Drawing",
        revision: "C",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-ECN",
        fileName: "ECN-2844.pdf",
        type: "ENGINEERING_CHANGE",
        title: "Engineering Change",
        revision: "2844",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-PF",
        fileName: "Process_Flow_RevC.pdf",
        type: "PROCESS_FLOW",
        title: "Process Flow",
        revision: "C",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-PFMEA",
        fileName: "PFMEA_SMH44721.xlsx",
        type: "PFMEA",
        title: "PFMEA",
        revision: "05",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-CP",
        fileName: "ControlPlan_SMH44721.xlsx",
        type: "CONTROL_PLAN",
        title: "Control Plan",
        revision: "04",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-MSA",
        fileName: "MSA_BoreDiameter.pdf",
        type: "MSA",
        title: "MSA",
        status: "PARTIAL",
        extractionConfidence: "MEDIUM",
      },
      {
        id: "DOC-DIM",
        fileName: "Dimensional_Report.xlsx",
        type: "DIMENSIONAL_RESULTS",
        title: "Dimensional Results",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-MAT",
        fileName: "Material_Certificate.pdf",
        type: "MATERIAL_RESULTS",
        title: "Material Certificate",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-CAP",
        fileName: "Capability_Study.xlsx",
        type: "CAPABILITY_STUDY",
        title: "Capability Study",
        status: "PRESENT",
        extractionConfidence: "MEDIUM",
      },
      {
        id: "DOC-CA",
        fileName: "Checking_Aids.pdf",
        type: "CHECKING_AIDS",
        title: "Checking Aids",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-CR",
        fileName: "Customer_Requirements.pdf",
        type: "CUSTOMER_REQUIREMENTS",
        title: "Customer Requirements",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
      {
        id: "DOC-PSW",
        fileName: "PSW_SMH44721.pdf",
        type: "PSW",
        title: "Part Submission Warrant",
        revision: "B",
        status: "PRESENT",
        extractionConfidence: "HIGH",
      },
    ],
    findings: [
      {
        id: "F-001",
        category: "Document Consistency",
        title: "Drawing / PSW revision mismatch",
        observation:
          "The engineering drawing references Revision C while the submitted PSW references Revision B.",
        preliminarySeverity: "CRITICAL_REVIEW",
        confidence: "HIGH",
        status: "AWAITING_SQE",
        recommendedNextStep:
          "Confirm whether the PSW must be reissued to Revision C before disposition.",
        evidence: [
          {
            id: "EV-001",
            documentId: "DOC-DRAWING",
            documentName: "SMH-44721_RevC_Drawing.pdf",
            label: "Drawing Revision",
            value: "C",
            page: 1,
            sourceReference: "Title Block",
            confidence: "HIGH",
          },
          {
            id: "EV-002",
            documentId: "DOC-PSW",
            documentName: "PSW_SMH44721.pdf",
            label: "Engineering Revision",
            value: "B",
            page: 1,
            sourceReference: "Engineering Change Level",
            confidence: "HIGH",
          },
        ],
        comments: [],
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: "F-002",
        category: "Material",
        title: "Material specification discrepancy",
        observation:
          "The drawing identifies material AlSi10Mg while the submitted material certificate identifies AlSi9Cu3.",
        preliminarySeverity: "CRITICAL_REVIEW",
        confidence: "HIGH",
        status: "AWAITING_SQE",
        recommendedNextStep:
          "Verify approved material specification and request corrected evidence if needed.",
        evidence: [
          {
            id: "EV-003",
            documentId: "DOC-DRAWING",
            documentName: "SMH-44721_RevC_Drawing.pdf",
            label: "Material",
            value: "AlSi10Mg",
            page: 1,
            sourceReference: "Material Note",
            confidence: "HIGH",
          },
          {
            id: "EV-004",
            documentId: "DOC-MAT",
            documentName: "Material_Certificate.pdf",
            label: "Material Grade",
            value: "AlSi9Cu3",
            page: 1,
            sourceReference: "Certificate Header",
            confidence: "HIGH",
          },
        ],
        comments: [],
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: "F-003",
        category: "Process Traceability",
        title: "Process operation not matched in PFMEA",
        observation:
          "Operation 40 - Laser Marking appears in the Process Flow and Control Plan but cannot be matched to the PFMEA.",
        preliminarySeverity: "MAJOR_REVIEW",
        confidence: "HIGH",
        status: "AWAITING_SQE",
        recommendedNextStep:
          "Request PFMEA update covering OP40 Laser Marking or confirm intentional exclusion.",
        evidence: [
          {
            id: "EV-005",
            documentId: "DOC-PF",
            documentName: "Process_Flow_RevC.pdf",
            label: "Operation",
            value: "OP40 Laser Marking",
            page: 1,
            sourceReference: "Process Flow Chart",
            confidence: "HIGH",
          },
          {
            id: "EV-006",
            documentId: "DOC-CP",
            documentName: "ControlPlan_SMH44721.xlsx",
            label: "Operation",
            value: "OP40 Laser Marking",
            sheet: "Control Plan",
            sourceReference: "Operation row",
            confidence: "HIGH",
          },
          {
            id: "EV-007",
            documentId: "DOC-PFMEA",
            documentName: "PFMEA_SMH44721.xlsx",
            label: "OP40 Match",
            value: "Not found",
            sheet: "PFMEA",
            sourceReference: "Operation search",
            confidence: "HIGH",
          },
        ],
        comments: [],
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: "F-004",
        category: "Characteristic Traceability",
        title: "Characteristic control requires review",
        observation:
          "Characteristic CC-07 Bore Diameter is identified in upstream evidence but its control relationship requires SQE verification.",
        preliminarySeverity: "MAJOR_REVIEW",
        confidence: "MEDIUM",
        status: "AWAITING_SQE",
        recommendedNextStep:
          "Inspect CC-07 characteristic chain and confirm MSA/gauge linkage.",
        evidence: [
          {
            id: "EV-008",
            documentId: "DOC-DRAWING",
            documentName: "SMH-44721_RevC_Drawing.pdf",
            label: "Requirement",
            value: "32.00 ± 0.05 mm",
            page: 2,
            sourceReference: "CC-07",
            confidence: "HIGH",
          },
          {
            id: "EV-009",
            documentId: "DOC-CP",
            documentName: "ControlPlan_SMH44721.xlsx",
            label: "Gauge",
            value: "G-104",
            sheet: "Control Plan",
            sourceReference: "CC-07 row",
            confidence: "HIGH",
          },
        ],
        comments: [],
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: "F-005",
        category: "MSA",
        title: "MSA evidence does not match Control Plan gauge",
        observation:
          "The Control Plan references Gauge G-104 while the submitted MSA evidence references Gauge G-102.",
        preliminarySeverity: "CLARIFICATION",
        confidence: "HIGH",
        status: "AWAITING_SQE",
        recommendedNextStep:
          "Request MSA for Gauge G-104 or clarification of gauge substitution.",
        evidence: [
          {
            id: "EV-010",
            documentId: "DOC-CP",
            documentName: "ControlPlan_SMH44721.xlsx",
            label: "Control Plan Gauge",
            value: "G-104",
            sheet: "Control Plan",
            sourceReference: "CC-07",
            confidence: "HIGH",
          },
          {
            id: "EV-011",
            documentId: "DOC-MSA",
            documentName: "MSA_BoreDiameter.pdf",
            label: "MSA Gauge",
            value: "G-102",
            page: 1,
            sourceReference: "Gauge ID",
            confidence: "HIGH",
          },
        ],
        comments: [],
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: "F-006",
        category: "PSW Completeness",
        title: "Incomplete PSW information",
        observation:
          "A required field defined by the demo submission profile is blank in the submitted PSW.",
        preliminarySeverity: "CLARIFICATION",
        confidence: "HIGH",
        status: "AWAITING_SQE",
        recommendedNextStep:
          "Identify the blank required field and request a completed PSW.",
        evidence: [
          {
            id: "EV-012",
            documentId: "DOC-PSW",
            documentName: "PSW_SMH44721.pdf",
            label: "Required Field",
            value: "(blank)",
            page: 1,
            sourceReference: "Submission Level / Reason section",
            confidence: "HIGH",
          },
        ],
        comments: [],
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    processTraceability: [
      {
        operationId: "OP10",
        operationNumber: "10",
        operationName: "Incoming Inspection",
        processFlow: { present: true, documentId: "DOC-PF", evidence: "OP10 listed" },
        pfmea: { present: true, documentId: "DOC-PFMEA", evidence: "OP10 listed" },
        controlPlan: { present: true, documentId: "DOC-CP", evidence: "OP10 listed" },
        status: "MATCHED",
      },
      {
        operationId: "OP20",
        operationNumber: "20",
        operationName: "CNC Machining",
        processFlow: { present: true, documentId: "DOC-PF", evidence: "OP20 listed" },
        pfmea: { present: true, documentId: "DOC-PFMEA", evidence: "OP20 listed" },
        controlPlan: { present: true, documentId: "DOC-CP", evidence: "OP20 listed" },
        status: "MATCHED",
      },
      {
        operationId: "OP30",
        operationNumber: "30",
        operationName: "Bore Machining",
        processFlow: { present: true, documentId: "DOC-PF", evidence: "OP30 listed" },
        pfmea: { present: true, documentId: "DOC-PFMEA", evidence: "OP30 listed" },
        controlPlan: { present: true, documentId: "DOC-CP", evidence: "OP30 listed" },
        status: "MATCHED",
      },
      {
        operationId: "OP40",
        operationNumber: "40",
        operationName: "Laser Marking",
        processFlow: { present: true, documentId: "DOC-PF", evidence: "OP40 listed" },
        pfmea: { present: false, evidence: "No matching PFMEA operation" },
        controlPlan: { present: true, documentId: "DOC-CP", evidence: "OP40 listed" },
        status: "REVIEW_REQUIRED",
      },
      {
        operationId: "OP50",
        operationNumber: "50",
        operationName: "Final Inspection",
        processFlow: { present: true, documentId: "DOC-PF", evidence: "OP50 listed" },
        pfmea: { present: true, documentId: "DOC-PFMEA", evidence: "OP50 listed" },
        controlPlan: { present: true, documentId: "DOC-CP", evidence: "OP50 listed" },
        status: "MATCHED",
      },
    ],
    characteristicTraceability: [
      {
        id: "CC-07",
        name: "Bore Diameter",
        drawing: {
          present: true,
          requirement: "32.00 ± 0.05 mm",
          evidence: "Drawing CC-07",
          documentId: "DOC-DRAWING",
        },
        pfmea: {
          present: true,
          operation: "OP30",
          evidence: "PFMEA OP30 Bore Diameter",
          documentId: "DOC-PFMEA",
        },
        controlPlan: {
          present: true,
          operation: "OP30",
          specification: "32.00 ± 0.05 mm",
          gauge: "G-104",
          evidence: "Control Plan CC-07",
          documentId: "DOC-CP",
        },
        dimensional: {
          present: true,
          result: "31.99 mm",
          evidence: "Dimensional report CC-07",
          documentId: "DOC-DIM",
        },
        msa: {
          present: false,
          gauge: "G-102",
          evidence: "No matching G-104 evidence",
          documentId: "DOC-MSA",
        },
        capability: {
          present: true,
          result: "Study submitted",
          evidence: "Capability study file present",
          documentId: "DOC-CAP",
        },
        status: "REVIEW_REQUIRED",
      },
    ],
    review: {
      status: "IN_REVIEW",
      startedAt: NOW,
    },
    auditTrail: [
      {
        id: "AUD-001",
        timestamp: NOW,
        action: "CASE_CREATED",
        entityType: "CASE",
        entityId: "PP-10482",
        actorType: "LANGDOCK",
        actor: "Langdock PPAP Agent",
        comment: "Automated analysis seeded demo case.",
      },
    ],
  };
}
